# Generated by Django 4.2.16 on 2024-11-11 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='auction_images/')),
                ('geolocation', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('Ювелирный', 'Ювелирный'), ('Историч ценный', 'Историч ценный'), ('Стандартный', 'Стандартный')], default='Стандартный', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=100)),
                ('end_time', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('user', 'User'), ('support', 'Support'), ('seller', 'Seller'), ('admin', 'Admin')], default='user', max_length=10)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('warnings', models.PositiveIntegerField(default=0)),
                ('succesful_trades', models.PositiveIntegerField(default=0)),
                ('chat_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('img_proof', models.ImageField(blank=True, null=True, upload_to='report_proofs/')),
                ('type', models.CharField(choices=[('user', 'User'), ('auction', 'Auction')], default='user', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaapp.auction')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='auction_images/')),
                ('geolocation', models.CharField(max_length=50)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('Ювелирный', 'Ювелирный'), ('Историч ценный', 'Историч ценный'), ('Стандартный', 'Стандартный')], default='Стандартный', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=100)),
                ('end_time', models.DateTimeField()),
                ('lots', models.ManyToManyField(to='monetaapp.auctionlot')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaapp.user')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='monetaapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='lots',
            field=models.ManyToManyField(to='monetaapp.auctionlot'),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaapp.user'),
        ),
    ]
