# Generated by Django 4.2.16 on 2024-11-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0003_remove_auctionhistory_lots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='lots',
        ),
    ]
