# Generated by Django 4.2.16 on 2024-11-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0004_remove_auction_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('User', 'User'), ('Support', 'Support'), ('Seller', 'Seller'), ('Admin', 'Admin')], default='User', max_length=10),
        ),
    ]
