# Generated by Django 4.2.16 on 2024-11-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0008_remove_report_img_proof_remove_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='message_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
