# Generated by Django 4.2.16 on 2024-11-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0009_auction_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hold_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
