# Generated by Django 4.2.16 on 2024-11-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0010_user_hold_balance_alter_auctionlot_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='product_image',
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction_images/')),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='monetaapp.auction')),
            ],
        ),
    ]
