# Generated by Django 4.2.16 on 2024-11-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0013_auctionhistory_ready_to_send_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
