# Generated by Django 4.2.16 on 2024-11-18 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0015_autobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionhistory',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monetaapp.auctionhistory')),
            ],
        ),
    ]
