# Generated by Django 4.2.16 on 2024-11-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0016_alter_auctionhistory_winner_orderdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
