# Generated by Django 4.2.16 on 2024-11-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monetaapp', '0017_auction_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdoc',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='monetaapp.auctionhistory'),
        ),
    ]
